language: —Åpp
sudo: required
dist: trusty

os: linux

script:
- cmake -H. -B_builds
- cmake --build _builds/
- cmake --build _builds/ --target test

addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
